[tool.black]
line-length = 88
target-version = ['py39', 'py310', 'py311']
include = '\.pyi?$'
extend-exclude = '''
/(
  migrations
  | venv
  | env
  | .env
  | .venv
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 88
known_first_party = ["controllers", "models", "common", "pages"]
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = "-v --tb=short"
filterwarnings = [
    "ignore::DeprecationWarning",
    "ignore::PendingDeprecationWarning"
]

[tool.bandit]
exclude_dirs = ["tests", "venv", "env", ".venv"]
skips = ["B101", "B601", "B110", "B307", "B324"]  # Skip assert_used, shell=True, try_except_pass, eval, md5

[tool.flake8]
max-line-length = 100
ignore = ["E501", "F841", "F541", "W291"]  # Temporalmente ignorar líneas largas, variables no usadas, f-strings sin placeholders, trailing whitespace
exclude = [
    ".git",
    "__pycache__",
    "venv",
    "env",
    ".venv",
    "migrations"
]
